/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@protocol PSController <NSObject>
@property(retain) id specifier;
@property(retain) id rootController;
@property(retain) id parentController;
- (void)statusBarWillAnimateByHeight:(float)statusBar;
- (BOOL)canBeShownFromSuspendedState;
- (void)willBecomeActive;
- (void)willResignActive;
- (id)readPreferenceValue:(id)value;
- (void)setPreferenceValue:(id)value specifier:(id)specifier;
- (void)handleURL:(id)url;
- (void)pushController:(id)controller;
- (void)didWake;
- (void)didUnlock;
- (void)willUnlock;
- (void)didLock;
- (void)suspend;
@end

