/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <UIKit/UITextView.h>
#import <UIKit/UITextField.h>
#import "PSTableCell.h"

@class PSListController, UIColor;

@interface PSEditableTableCell : PSTableCell <UITextViewDelegate, UITextFieldDelegate> {
	UIColor *_textColor;
	id _delegate;
	BOOL _forceFirstResponder;
	BOOL _delaySpecifierRelease;
	SEL _targetSetter;
	id _realTarget;
	BOOL _valueChanged;
@private
	BOOL _returnKeyTapped;
	PSListController *_controllerDelegate;
}
@property(assign, nonatomic) PSListController *controllerDelegate;
@property(readonly, assign, nonatomic) BOOL returnKeyTapped;
- (id)textField;
- (void)setPlaceholderText:(id)text;
- (BOOL)_cellIsEditing;
- (BOOL)isEditing;
- (BOOL)isTextFieldEditing;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)isFirstResponder;
- (BOOL)canResignFirstResponder;
- (void)setDelegate:(id)delegate;
- (void)_saveForExit;
- (void)_setValueChanged;
- (void)endEditingAndSave;
- (void)controlChanged:(id)changed;
@end

