/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSListController.h"

@interface PSEditableListController : PSListController {
	BOOL _editable;
	BOOL _editingDisabled;
}
@property(assign) BOOL editable;
- (void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
- (BOOL)performDeletionActionForSpecifier:(id)specifier;
- (int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
- (id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
- (void)_setEditable:(BOOL)editable animated:(BOOL)animated;
- (void)editDoneTapped;
- (void)setEditButtonEnabled:(BOOL)enabled;
- (void)setEditingButtonHidden:(BOOL)hidden animated:(BOOL)animated;
- (void)_updateNavigationBar;
- (id)_editButtonBarItem;
@end

