/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSListController.h"

@class UILabel, NSArray;

@interface PSLargeTextController : PSListController {
@private
	UILabel *_bodyExampleLabel;
	UILabel *_headlineExampleLabel;
	int _selectedCategoryIndex;
	NSArray *_contentSizeCategories;
	BOOL _usesExtendedRange;
	BOOL _showsExtendedRangeSwitch;
}
@property(assign, nonatomic) BOOL showsExtendedRangeSwitch;
- (id)usesExtendedRangeForSpecifier:(id)specifier;
- (void)setUsesExtendedRange:(id)range forSpecifier:(id)specifier;
- (id)getDynamicTypeValueForSpecifier:(id)specifier;
- (void)setDynamicTypeValue:(id)value forSpecifier:(id)specifier;
- (void)updateExampleFonts;
- (void)sizeCategoryDidChange:(id)sizeCategory;
@end

