/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSListController.h"

@class PSSpecifier;

@interface PSListItemsController : PSListController {
	int _rowToSelect;
	BOOL _deferItemSelection;
	BOOL _restrictionList;
	PSSpecifier *_lastSelectedSpecifier;
}
@property(assign) BOOL isRestrictionList;
- (id)itemsFromDataSource;
- (id)itemsFromParent;
- (void)_addStaticText:(id)text;
- (void)listItemSelected:(id)selected;
- (void)setValueForSpecifier:(id)specifier defaultValue:(id)value;
- (void)setRowToSelect;
- (void)scrollToSelectedCell;
@end

