/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSViewController.h"
#import "PSViewControllerOffsetProtocol.h"
#import <UIKit/UITableView.h>
#import <UIKit/UIActionSheet.h>
#import <UIKit/UIAlertView.h>
#import <UIKit/UIPopoverController.h>

@class NSString, NSArray, NSMutableDictionary, NSMutableArray, UIView, UITableView, UIActionSheet, UIAlertView, UIKeyboard, UIPopoverController;

@interface PSListController : PSViewController <UITableViewDelegate, UITableViewDataSource, UIActionSheetDelegate, UIAlertViewDelegate, UIPopoverControllerDelegate, PSViewControllerOffsetProtocol> {
	NSMutableArray *_prequeuedReusablePSTableCells;
	NSMutableDictionary *_cells;
	BOOL _cachesCells;
	BOOL _reusesCells;
	BOOL _forceSynchronousIconLoadForCreatedCells;
	UIView *_containerView;
	UITableView *_table;
	NSArray *_specifiers;
	NSMutableDictionary *_specifiersByID;
	NSMutableArray *_groups;
	NSString *_specifierID;
	NSMutableArray *_bundleControllers;
	BOOL _bundlesLoaded;
	BOOL _showingSetupController;
	UIActionSheet *_actionSheet;
	UIAlertView *_alertView;
	BOOL _swapAlertButtons;
	BOOL _keyboardWasVisible;
	UIKeyboard *_keyboard;
	UIPopoverController *_popupStylePopoverController;
	BOOL _popupStylePopoverShouldRePresent;
	BOOL _popupIsModal;
	BOOL _popupIsDismissing;
	BOOL _hasAppeared;
	float _verticalContentOffset;
	NSString *_offsetItemName;
	CGPoint _contentOffsetWithKeyboard;
@private
	BOOL _edgeToEdgeCells;
}
@property(assign, nonatomic) BOOL edgeToEdgeCells;
@property(assign, nonatomic) BOOL forceSynchronousIconLoadForCreatedCells;
@property(retain) NSString *specifierID;
@property(retain) NSArray *specifiers;
@property(readonly, retain) UITableView *table;
@property(readonly, retain) UIPopoverController *popupStylePopoverController;
+ (BOOL)displaysButtonBar;
- (void)_setNotShowingSetupController;
- (BOOL)shouldReloadSpecifiersOnResume;
- (void)selectRowForSpecifier:(id)specifier;
- (void)_keyboardDidHide:(id)_keyboard;
- (void)_keyboardWillHide:(id)_keyboard;
- (void)_keyboardWillShow:(id)_keyboard;
- (void)_setContentInset:(float)inset;
- (float)_getKeyboardIntersectionHeight;
- (void)reloadIconForSpecifierForBundle:(id)bundle;
- (void)dismissPopoverAnimated:(BOOL)animated;
- (void)dismissPopover;
- (void)popoverController:(id)controller animationCompleted:(int)completed;
- (void)pushController:(id)controller animate:(BOOL)animate;
- (id)specifierForID:(id)anId;
- (id)controllerForSpecifier:(id)specifier;
- (id)controllerForRowAtIndexPath:(id)indexPath;
- (void)lazyLoadBundle:(id)bundle;
- (void)_handleActionSheet:(id)sheet clickedButtonAtIndex:(int)index;
- (void)confirmationViewCancelledForSpecifier:(id)specifier;
- (void)confirmationViewAcceptedForSpecifier:(id)specifier;
- (void)dismissConfirmationViewForSpecifier:(id)specifier animated:(BOOL)animated;
- (void)showConfirmationViewForSpecifier:(id)specifier;
- (void)showConfirmationViewForSpecifier:(id)specifier useAlert:(BOOL)alert swapAlertButtons:(BOOL)buttons;
- (BOOL)performConfirmationCancelActionForSpecifier:(id)specifier;
- (BOOL)performConfirmationActionForSpecifier:(id)specifier;
- (BOOL)performButtonActionForSpecifier:(id)specifier;
- (BOOL)performLoadActionForSpecifier:(id)specifier;
- (BOOL)performActionForSpecifier:(id)specifier;
- (void)_returnKeyPressed:(id)pressed;
- (void)returnPressedAtEnd;
- (void)viewWillDisappear:(BOOL)view;
- (void)viewDidAppear:(BOOL)view;
- (void)prepareSpecifiersMetadata;
- (void)viewDidLoad;
- (id)findFirstVisibleResponder;
- (BOOL)shouldSelectResponderOnAppearance;
- (void)_scrollToSpecifierNamed:(id)specifierNamed;
- (void)viewWillAppear:(BOOL)view;
- (void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
- (void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
- (id)_tableView:(id)view viewForCustomInSection:(int)section isHeader:(BOOL)header;
- (float)_tableView:(id)view heightForCustomInSection:(int)section isHeader:(BOOL)header;
- (id)_customViewForSpecifier:(id)specifier class:(Class)aClass isHeader:(BOOL)header;
- (int)tableView:(id)view titleAlignmentForFooterInSection:(int)section;
- (int)tableView:(id)view titleAlignmentForHeaderInSection:(int)section;
- (id)tableView:(id)view detailTextForHeaderInSection:(int)section;
- (void)createPrequeuedPSTableCells:(unsigned)cells;
- (id)cachedCellForSpecifierID:(id)specifierID;
- (id)cachedCellForSpecifier:(id)specifier;
- (void)setTitle:(id)title;
- (void)reloadSpecifiers;
- (void)migrateSpecifierMetadataFrom:(id)from to:(id)to;
- (void)reload;
- (void)loseFocus;
- (void)createGroupIndices;
- (id)_createGroupIndices:(id)indices;
- (void)viewDidUnload;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (Class)tableViewClass;
- (id)initForContentSize:(CGSize)contentSize;
- (id)init;
- (void)_unloadBundleControllers;
- (void)_loadBundleControllers;
- (void)updateSpecifiersInRange:(NSRange)range withSpecifiers:(id)specifiers;
- (void)updateSpecifiers:(id)specifiers withSpecifiers:(id)specifiers2;
- (int)_nextGroupInSpecifiersAfterIndex:(int)specifiersAfterIndex inArray:(id)array;
- (void)replaceContiguousSpecifiers:(id)specifiers withSpecifiers:(id)specifiers2 animated:(BOOL)animated;
- (void)replaceContiguousSpecifiers:(id)specifiers withSpecifiers:(id)specifiers2;
- (void)removeContiguousSpecifiers:(id)specifiers;
- (void)removeContiguousSpecifiers:(id)specifiers animated:(BOOL)animated;
- (void)_removeContiguousSpecifiers:(id)specifiers animated:(BOOL)animated;
- (void)removeLastSpecifierAnimated:(BOOL)animated;
- (void)removeLastSpecifier;
- (void)removeSpecifierAtIndex:(int)index;
- (void)removeSpecifierID:(id)anId;
- (void)removeSpecifier:(id)specifier;
- (void)removeSpecifierAtIndex:(int)index animated:(BOOL)animated;
- (void)removeSpecifierID:(id)anId animated:(BOOL)animated;
- (void)removeSpecifier:(id)specifier animated:(BOOL)animated;
- (void)addSpecifiersFromArray:(id)array animated:(BOOL)animated;
- (void)addSpecifiersFromArray:(id)array;
- (void)addSpecifier:(id)specifier animated:(BOOL)animated;
- (void)addSpecifier:(id)specifier;
- (void)insertContiguousSpecifiers:(id)specifiers atEndOfGroup:(int)group;
- (void)insertContiguousSpecifiers:(id)specifiers afterSpecifierID:(id)anId;
- (void)insertContiguousSpecifiers:(id)specifiers afterSpecifier:(id)specifier;
- (void)insertContiguousSpecifiers:(id)specifiers atIndex:(int)index;
- (void)insertContiguousSpecifiers:(id)specifiers atEndOfGroup:(int)group animated:(BOOL)animated;
- (void)insertContiguousSpecifiers:(id)specifiers afterSpecifierID:(id)anId animated:(BOOL)animated;
- (void)insertContiguousSpecifiers:(id)specifiers afterSpecifier:(id)specifier animated:(BOOL)animated;
- (void)insertContiguousSpecifiers:(id)specifiers atIndex:(int)index animated:(BOOL)animated;
- (void)_insertContiguousSpecifiers:(id)specifiers atIndex:(int)index animated:(BOOL)animated;
- (void)insertSpecifier:(id)specifier atEndOfGroup:(int)group;
- (void)insertSpecifier:(id)specifier afterSpecifierID:(id)anId;
- (void)insertSpecifier:(id)specifier afterSpecifier:(id)specifier2;
- (void)insertSpecifier:(id)specifier atIndex:(int)index;
- (void)insertSpecifier:(id)specifier atEndOfGroup:(int)group animated:(BOOL)animated;
- (void)insertSpecifier:(id)specifier afterSpecifierID:(id)anId animated:(BOOL)animated;
- (void)insertSpecifier:(id)specifier afterSpecifier:(id)specifier2 animated:(BOOL)animated;
- (void)insertSpecifier:(id)specifier atIndex:(int)index animated:(BOOL)animated;
- (id)specifiersInGroup:(int)group;
- (int)rowsForGroup:(int)group;
- (int)indexForRow:(int)row inGroup:(int)group;
- (BOOL)getGroup:(int *)group row:(int *)row ofSpecifierAtIndex:(int)index;
- (BOOL)_getGroup:(int *)group row:(int *)row ofSpecifierAtIndex:(int)index groups:(id)groups;
- (BOOL)getGroup:(int *)group row:(int *)row ofSpecifier:(id)specifier;
- (BOOL)getGroup:(int *)group row:(int *)row ofSpecifierID:(id)specifierID;
- (id)specifierAtIndex:(int)index;
- (int)numberOfGroups;
- (int)indexOfGroup:(int)group;
- (BOOL)containsSpecifier:(id)specifier;
- (int)indexOfSpecifier:(id)specifier;
- (int)indexOfSpecifierID:(id)specifierID;
- (void)reloadSpecifierID:(id)anId;
- (void)reloadSpecifierID:(id)anId animated:(BOOL)animated;
- (void)reloadSpecifier:(id)specifier;
- (void)reloadSpecifier:(id)specifier animated:(BOOL)animated;
- (void)reloadSpecifierAtIndex:(int)index;
- (void)reloadSpecifierAtIndex:(int)index animated:(BOOL)animated;
- (void)endUpdates;
- (void)beginUpdates;
- (int)indexForIndexPath:(id)indexPath;
- (id)indexPathForSpecifier:(id)specifier;
- (id)indexPathForIndex:(int)index;
- (void)_removeIdentifierForSpecifier:(id)specifier;
- (void)_addIdentifierForSpecifier:(id)specifier;
- (id)loadSpecifiersFromPlistName:(id)plistName target:(id)target;
- (id)bundle;
- (void)setCachesCells:(BOOL)cells;
- (void)setReusesCells:(BOOL)cells;
- (void)clearCache;
- (void)showPINSheet:(id)sheet;
@end

