/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSTableCell.h"

@class UIActivityIndicatorView;

@interface PSSpinnerTableCell : PSTableCell {
@private
	UIActivityIndicatorView *_spinner;
}
- (id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

