/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@class UILongPressGestureRecognizer, NSString, PSSpecifier, UIImageView;

@interface PSTableCell : NSObject {
	id _value;
	UIImageView *_checkedImageView;
	BOOL _checked;
	BOOL _shouldHideTitle;
	NSString *_hiddenTitle;
	int _alignment;
	SEL _pAction;
	id _pTarget;
	BOOL _cellEnabled;
	PSSpecifier *_specifier;
	int _type;
	BOOL _lazyIcon;
	BOOL _lazyIconDontUnload;
	BOOL _lazyIconForceSynchronous;
	NSString *_lazyIconAppID;
	BOOL _reusedCell;
@private
	BOOL _isCopyable;
	UILongPressGestureRecognizer *_longTapRecognizer;
}
@property(retain, nonatomic) UILongPressGestureRecognizer *longTapRecognizer;
@property(assign, nonatomic) BOOL isCopyable;
@property(assign, nonatomic) BOOL reusedCell;
@property(retain, nonatomic) PSSpecifier *specifier;
@property(assign, nonatomic) int type;
@property(assign) BOOL cellEnabled;
@property(assign) SEL cellAction;
@property(retain) id cellTarget;
@property(assign) SEL action;
@property(retain) id target;
@property(retain) id value;
@property(assign, getter=isChecked) BOOL checked;
@property(retain) id title;
+ (Class)cellClassForSpecifier:(id)specifier;
+ (int)cellStyle;
+ (id)reuseIdentifierForSpecifier:(id)specifier;
+ (id)reuseIdentifierForClassAndType:(int)classAndType;
+ (id)reuseIdentifierForBasicCellTypes:(int)basicCellTypes;
+ (id)stringFromCellType:(int)cellType;
+ (int)cellTypeFromString:(id)string;
- (float)textFieldOffset;
- (void)reloadWithSpecifier:(id)specifier animated:(BOOL)animated;
- (void)setAlignment:(int)alignment;
- (id)iconImageView;
- (id)valueLabel;
- (id)titleLabel;
- (void)setIcon:(id)icon;
- (BOOL)canBeChecked;
- (void)setShouldHideTitle:(BOOL)hideTitle;
- (id)getIcon;
- (void)forceSynchronousIconLoadOnNextIconLoad;
- (void)cellRemovedFromView;
- (id)blankIcon;
- (id)getLazyIconID;
- (id)getLazyIcon;
- (id)_contentString;
- (BOOL)canReload;
- (void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (id)titleTextLabel;
- (void)setValueChangedTarget:(id)target action:(SEL)action specifier:(id)specifier;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)refreshCellContentsWithSpecifier:(id)specifier;
- (BOOL)canPerformAction:(SEL)action withSender:(id)sender;
- (void)copy:(id)copy;
- (id)_copyableText;
- (void)longPressed:(id)pressed;
- (BOOL)canBecomeFirstResponder;
- (void)dealloc;
- (id)initWithStyle:(int)style reuseIdentifier:(id)identifier specifier:(id)specifier;
- (id)scriptingInfoWithChildren;
- (id)_automationID;
@end

