
#import <Foundation/Foundation.h>

@class PCPersistentTimer, UILocalNotification, BKSProcessAssertion, BKSApplicationDataStore, NSHashTable, NSString, NSArray, SBWindowContextManager, SBActivationContext, NSMutableDictionary, NSTimer, NSMapTable, NSMutableSet, NSMutableArray, NSDictionary, NSSet, BKSCFBundle, BKSMachSendRight, NSDate, UIRemoteApplication;

@interface SBApplication : NSObject
@property(copy) NSString *displayIdentifier;
@property(copy, nonatomic) SBActivationContext *activationContext;
@property(retain, nonatomic) BKSMachSendRight *xpcEventPort;
@property(readonly, assign, nonatomic) int pid;
@property(assign) BOOL showsProgress;
@property(assign) BOOL proximityEventsEnabled;
@property(assign) BOOL orientationChangedEventsEnabled;
@property(assign) double accelerometerSampleInterval;
@property(assign) BOOL expectsFaceContact;
@property(assign) BOOL hasBeenFrontmost;
@property(assign) unsigned applicationState;
@property(retain) NSString *sandboxPath;
@property(retain) id applicationNextWakeDate;
@property(assign, getter=isRunning) BOOL running;
@property(assign, getter=isBeingDebugged) BOOL beingDebugged;
@property(retain) NSString *displayName;
@property(assign) BOOL hasShownDataPlanAlertSinceLock;
@property(retain) NSSet *alertSuppressionContexts;
@property(assign) BOOL hasMiniAlerts;
@property(retain) NSArray *tags;
@property(assign) BOOL enabled;
@property(readonly, retain) NSString *bundleIdentifier;
@property(readonly, retain) NSString *path;
@property(readonly, retain) NSString *bundleVersion;
@property(readonly, retain) NSArray *folderNames;
@property(readonly, retain) NSString *fallbackFolderName;
@property(readonly, assign) int activationState;
@property(readonly, assign) double modificationDate;
@property(readonly, retain) UIRemoteApplication *remoteApplication;
@property(readonly, retain) NSString *signerIdentity;
@property(readonly, assign) BOOL defaultStatusBarHidden;
@property(readonly, assign) int ratingRank;
@property(readonly, assign) Class iconClass;
@property(readonly, retain) NSArray *externalAccessoryProtocols;
@property(readonly, assign) double lastBadgeClearTime;
@property(readonly, retain) NSMutableSet *idleTimerDisabledReasons;
@property(readonly, assign) float minimumBrightnessLevel;
@property(readonly, retain) NSArray *domainsToPreheat;
+ (id)defaultValueForKey:(id)key displayIdentifier:(id)identifier urlScheme:(id)scheme;
+ (void)setDefaultValue:(id)value forKey:(id)key displayIdentifier:(id)identifier;
+ (BOOL)shouldHaveContextsForActivationState:(int)activationState;
+ (BOOL)activationStateIsTransitory:(int)transitory;
+ (id)appStateKeysToPrefetch;
+ (void)initialize;
+ (void)removalTimerFired:(id)fired;
+ (void)setRemovalTimer:(double)timer forSnapshotWithPath:(id)path;
+ (void)removeCachedSnapshotsMatchingPath:(id)path;
+ (void)removeCachedSnapshotsForScreen:(id)screen;
+ (void)removeCachedSnapshotSurfaceForPath:(id)path;
+ (void)removeCachedSnapshotSurface:(void *)surface forPath:(id)path;
+ (void)setCachedSnapshotSurface:(void *)surface forPath:(id)path;
+ (void)setCachedSnapshotSurface:(void *)surface forPath:(id)path purgeAfter:(double)after;
+ (void *)cachedSnapshotSurfaceForPath:(id)path;
+ (id)systemSnapshotsDirectory;
- (void)windowContextManager:(id)manager didStopTrackingContextsForScreen:(id)screen;
- (void)windowContextManager:(id)manager willStartTrackingContextsForScreen:(id)screen;
- (BOOL)windowContextManager:(id)manager shouldAddContext:(id)context;
- (void)screenManager:(id)manager didReconnectScreen:(id)screen;
- (void)screenManager:(id)manager didDisconnectScreen:(id)screen;
- (void)screenManager:(id)manager didChangeSuppressionOfScreen:(id)screen;
- (BOOL)canAccessScreen:(id)screen;
- (BOOL)icon:(id)icon launchFromLocation:(int)location;
- (BOOL)iconAllowsLaunch:(id)launch;
- (BOOL)iconCompleteUninstall:(id)uninstall;
- (BOOL)iconAllowsUninstall:(id)uninstall;
- (BOOL)iconIsRecentlyUpdated:(id)updated;
- (id)iconFormattedAccessoryString:(id)string;
- (id)iconBadgeNumberOrString:(id)string;
- (int)iconAccessoryType:(id)type;
- (BOOL)iconProgressIsPaused:(id)paused;
- (float)iconProgressPercent:(id)percent;
- (int)iconProgressState:(id)state;
- (BOOL)iconAppearsInNewsstand:(id)newsstand;
- (BOOL)iconCanEllipsizeLabel:(id)label;
- (id)icon:(id)icon defaultImageWithFormat:(int)format;
- (id)icon:(id)icon imageWithFormat:(int)format;
- (unsigned)iconPriority:(id)priority;
- (id)iconDisplayName:(id)name;
- (void)popActivationContext;
- (void)pushActivationContext;
- (BOOL)supportsStarkGateKeeper;
- (BOOL)supportsStarkFullScreen;
- (id)deactivationSettingsDescription;
- (id)descriptionForDeactivationSetting:(unsigned)deactivationSetting;
- (id)activationSettingsDescription;
- (id)descriptionForActivationSetting:(unsigned)activationSetting;
- (id)displaySettingsDescription;
- (id)descriptionForDisplaySetting:(unsigned)displaySetting;
- (id)description;
- (id)deactivationSettings;
- (id)activationSettings;
- (id)launchSettings;
- (unsigned)eventPort;
- (BOOL)hasStartedLaunching;
- (BOOL)isRecordingAudio;
- (BOOL)suppressesControlCenter;
- (BOOL)suppressesNotificationCenter;
- (BOOL)suppressesBanners;
- (BOOL)showSystemVolumeHUDForCategory:(id)category;
- (void)setSystemVolumeHUDEnabled:(BOOL)enabled forCategory:(id)category;
- (BOOL)expectsFaceContactInLandscape;
- (void)setExpectsFaceContact:(BOOL)contact inLandscape:(BOOL)landscape;
- (void)deactivate;
- (void)activate;
- (void)setIdleTimerDisabled:(BOOL)disabled forReason:(id)reason;
- (BOOL)isTranslucent;
- (int)wallpaperStyle;
- (BOOL)setWallpaperStyleForBackgroundStyle:(int)backgroundStyle;
- (int)launchingInterfaceOrientationForCurrentOrientation;
- (BOOL)allowsEventOnlySuspension;
- (BOOL)deactivationFlag:(unsigned)flag;
- (id)deactivationValue:(unsigned)value;
- (void)setDeactivationSetting:(unsigned)setting value:(id)value;
- (void)setDeactivationSetting:(unsigned)setting flag:(BOOL)flag;
- (void)clearDeactivationSettings;
- (void)markUserLaunchInitiationTime;
- (BOOL)activationFlag:(unsigned)flag;
- (id)activationValue:(unsigned)value;
- (void)setActivationSetting:(unsigned)setting value:(id)value;
- (void)setActivationSetting:(unsigned)setting flag:(BOOL)flag;
- (void)clearActivationSettings;
- (BOOL)displayFlag:(unsigned)flag;
- (id)displayValue:(unsigned)value;
- (void)setDisplaySetting:(unsigned)setting value:(id)value;
- (void)setDisplaySetting:(unsigned)setting flag:(BOOL)flag;
- (void)clearDisplaySettings;
- (id)urlScheme;
- (id)copyWithZone:(NSZone *)zone;
- (id)defaultImagePathForSnapshotWithName:(id)name screen:(id)screen;
- (int)interfaceOrientationForScreen:(id)screen;
- (void)sendSimpleRemoteAction:(int)action;
- (void)takeAssertionWithTimeoutForSimpleRemoteAction;
- (void)setNowPlayingWithAudio:(BOOL)audio;
- (void)resumeForContentAvailable;
- (void)resumeToQuit;
- (void)notifyResumeActiveForReason:(int)reason;
- (void)notifyResignActiveForReason:(int)reason;
- (BOOL)isCacheCleaningTerminationAssertionHeld;
- (BOOL)isAnyTerminationAssertionHeld;
- (void)resetLaunchAlertForType:(int)type;
- (BOOL)showLaunchAlertForType:(int)type;
- (void)prepareForUninstallation;
- (BOOL)provisioningProfileValidated;
- (void)markApplicationIdentityAsTrusted;
- (int)applicationSignatureState;
- (BOOL)wantsUnboundedTaskCompletionAssertions;
- (BOOL)supportsContinuousBackgroundMode;
- (BOOL)supportsFetchBackgroundMode;
- (BOOL)supportsRemoteNotificationBackgroundMode;
- (BOOL)supportsEABackgroundMode;
- (BOOL)supportsVOIPBackgroundMode;
- (BOOL)supportsLocationBackgroundMode;
- (BOOL)supportsAudioBackgroundMode;
- (BOOL)isActivating;
- (id)preferenceDomain;
- (void)hostContextsOnScreen:(id)screen forRequester:(id)requester;
- (id)mainScreenContextHostManager;
- (id)contextHostManagerForScreen:(id)screen;
- (id)contextManagerCreatingIfNecessary:(BOOL)necessary;
- (id)getPendingLocalNotification;
- (void)systemLocalNotificationAlertShouldSnooze:(id)systemLocalNotificationAlert;
- (void)systemLocalNotificationAlertShouldLaunch:(id)systemLocalNotificationAlert;
- (void)localNotificationTimerFired;
- (void)setBadge:(id)badge;
- (id)badgeNumberOrString;
- (BOOL)badgeHasBeenSetLocally;
- (void)noteBadgeSetLocally;
- (BOOL)usesLocalNotifications;
- (BOOL)supportsLocalNotifications;
- (void)cancelLocalNotification:(id)notification;
- (void)scheduleLocalNotifications:(id)notifications replaceExistingNotifications:(BOOL)notifications2;
- (id)scheduledLocalNotifications;
- (id)loggingIdentifier;
- (void)noteDidOpenURL:(id)note;
- (void)spdResumeForTrafficRequested;
- (void)wakeTimerFired;
- (BOOL)classicDefaultStatusBarHidden;
- (BOOL)classicAppZoomedInOrRequiresHiDPI;
- (BOOL)classicAppRequiresHiDPI;
- (BOOL)classicAppZoomedIn;
- (BOOL)supportsApplicationType:(int)type;
- (BOOL)isClassic;
- (int)launchingInterfaceOrientationForOrientation:(int)orientation;
- (void)removeDefaultInterfaceOrientationOverride;
- (void)overrideDefaultInterfaceOrientation:(int)orientation;
- (int)starkStatusBarStyle;
- (int)statusBarOrientation;
- (BOOL)statusBarHidden;
- (id)statusBarEffectiveStyleRequestWithStyleOverrides:(int)styleOverrides;
- (id)effectiveStatusBarStyleRequest;
- (int)effectiveStatusBarStyle;
- (id)statusBarStyleRequest;
- (int)statusBarStyle;
- (int)defaultStatusBarStyle;
- (void)autoLaunchIfNecessaryOnBootOrInstall:(BOOL)install;
- (BOOL)shouldAutoRelaunchAfterExit;
- (BOOL)shouldAutoLaunchOnBootOrInstall;
- (void)markRecentlyUpdated;
- (void)markNewlyInstalled;
- (void)didAnimateDeactivationOnStarkScreenController:(id)controller;
- (void)willAnimateDeactivationOnStarkScreenController:(id)controller;
- (void)didAnimateActivationOnStarkScreenController:(id)controller;
- (void)willAnimateActivationOnStarkScreenController:(id)controller;
- (void)didAnimateDeactivation;
- (void)willAnimateDeactivation:(BOOL)deactivation;
- (void)didAnimateActivation;
- (void)willAnimateActivation;
- (void)finishedBackgroundContentFetchingWithInfo:(id)info;
- (void)didDeactivateForEventsOnly:(BOOL)eventsOnly;
- (void)willDeactivateForEventsOnly:(BOOL)eventsOnly;
- (void)didFailToActivate;
- (void)didActivate;
- (void)willActivate;
- (void)didSuspend;
- (void)didExitWithInfo:(id)info type:(int)type;
- (void)didLaunch:(id)launch;
- (void)didBeginLaunch:(id)launch;
- (void)setProcessInfo:(id)info;
- (id)defaultImageForScreen:(id)screen snapshot:(BOOL *)snapshot originalOrientation:(int *)orientation currentOrientation:(int *)orientation4 canUseIOSurface:(BOOL)surface;
- (BOOL)shouldLaunchPNGless;
- (void)flushSnapshotsForScreen:(id)screen;
- (void)flushSnapshotsForAllScreens;
- (id)appSnapshotPathForScreen:(id)screen;
- (id)customSpotlightIconPathsForKey:(id)key;
- (void)validateSystemProvisioningEntitlements:(void *)entitlements;
- (BOOL)isLaunchableDuringSetup;
- (BOOL)hasGameCenterData;
- (BOOL)isNowRecordingApplication;
- (id)webClip;
- (BOOL)isWebApplication;
- (BOOL)behavesLikePhone;
- (BOOL)isFaceTime;
- (BOOL)isMobilePhone;
- (BOOL)isSystemProvisioningApplication;
- (BOOL)isInternalApplication;
- (BOOL)isSystemApplication;
- (void)setUsesWiFiNetwork:(BOOL)network;
- (void)setUsesEdgeNetwork:(BOOL)network;
- (void)setUsesBackgroundNetwork:(BOOL)network;
- (int)dataUsage;
- (BOOL)suspendingUnsupported;
- (void)purgeAllCaches;
- (void)purgeBundleCaches;
- (id)bundle;
- (id)containerPath;
- (BOOL)isSameExecutableAsApplication:(id)application;
- (void)dealloc;
- (double)autoLockTime;
- (double)autoDimTime;
- (id)initWithBundleIdentifier:(id)bundleIdentifier webClip:(id)clip path:(id)path bundle:(id)bundle infoDictionary:(id)dictionary isSystemApplication:(BOOL)application signerIdentity:(id)identity provisioningProfileValidated:(BOOL)validated entitlements:(id)entitlements;
- (BOOL)isNewsstandApplication;
- (BOOL)isSnapshotPresentForLaunchingInterfaceOrientation:(int)launchingInterfaceOrientation;
- (id)fileSnapshotForImageInfo:(id)imageInfo originalOrientation:(out int *)orientation currentOrientation:(out int *)orientation3;
- (id)cachedSnapshotForImageInfo:(id)imageInfo originalOrientation:(out int *)orientation currentOrientation:(out int *)orientation3;
- (id)snapshotImageInfosWithImageName:(id)imageName forScreen:(id)screen launchingOrientation:(int)orientation;
@end
